# Generated by Django 2.1.2 on 2018-10-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_modern_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Admin Profile', 'verbose_name_plural': 'Admin Profile'},
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
