# Generated by Django 2.1.2 on 2018-10-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_modern_admin', '0002_auto_20181010_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='AdminLogo')),
            ],
            options={
                'verbose_name': 'Admin Logo',
                'verbose_name_plural': 'Admin Logo',
            },
        ),
    ]
