# Generated by Django 2.1.2 on 2018-10-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_modern_admin', '0004_auto_20181010_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLoginLogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='AdminLoginLogo')),
            ],
            options={
                'verbose_name': 'Admin Login Logo',
                'verbose_name_plural': 'Admin Login Logo',
            },
        ),
    ]
