# Generated by Django 2.1.2 on 2018-10-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_modern_admin', '0006_admintasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintasks',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
