# Generated by Django 2.1.2 on 2018-10-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderPrice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orders',
            name='orderTotal',
            field=models.IntegerField(default=0),
        ),
    ]
