# Generated by Django 2.1.2 on 2018-10-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0004_auto_20181012_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderCategory',
            field=models.CharField(choices=[('Phone', 'Phone'), ('Computer', 'Computer'), ('Television', 'Television')], default='Phone', max_length=50),
            preserve_default=False,
        ),
    ]
