# Generated by Django 2.1.2 on 2018-10-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_orders_ordercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderCity',
            field=models.CharField(choices=[('Istanbul', 'Istanbul'), ('Ankara', 'Ankara')], default='Istanbul', max_length=150),
            preserve_default=False,
        ),
    ]
